services:
  postgres:
    image: postgres:17
    container_name: commerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d commerce"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: commerce-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: apache/kafka:4.0.0
    container_name: commerce-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  order-service:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: commerce-order-service
    restart: unless-stopped
    environment:
      APP_ENV: development
      APP_NAME: event-driven-commerce-platform
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/commerce
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  db-migrate:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: commerce-db-migrate
    command: ["alembic", "upgrade", "head"]
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/commerce
    depends_on:
      postgres:
        condition: service_healthy

  outbox-publisher:
    build:
      context: ../../services/order-service
      dockerfile: Dockerfile
    container_name: commerce-outbox-publisher
    restart: unless-stopped
    command: ["python", "-m", "app.messaging.publisher_main"]
    environment:
      APP_ENV: development
      APP_NAME: event-driven-commerce-platform-outbox-publisher
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/commerce
      REDIS_URL: redis://redis:6379/0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  notification-service:
    build:
      context: ../../services/notification-service
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/notification
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  kafka_data: